# Netlify Configuration
[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Caché para CSS y JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Caché para imágenes
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML con caché corto
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirecciones
[[redirects]]
  from = "/servicios"
  to = "/#servicios"
  status = 301

[[redirects]]
  from = "/contacto"
  to = "/#contacto"
  status = 301

[[redirects]]
  from = "/sobre-nosotros"
  to = "/#sobre-nosotros"
  status = 301

# Manejo de errores
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
